version: "3"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db/postgres:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      ANNICT_ACCESS_TOKEN: ${ANNICT_ACCESS_TOKEN}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    tty: true
    stdin_open: true
    depends_on:
      - db
